#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE xdigital;
    GRANT ALL PRIVILEGES ON DATABASE xdigital TO $POSTGRES_USER;

    \c task_assignment_db;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER;
EOSQL
